<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country')->insert(['cnt_name' => 'Afghanistan', 'cnt_iso' => 'AF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Aland Islands', 'cnt_iso' => 'AX', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Albania', 'cnt_iso' => 'AL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Algeria', 'cnt_iso' => 'DZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'American Samoa', 'cnt_iso' => 'AS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Andorra', 'cnt_iso' => 'AD', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Angola', 'cnt_iso' => 'AO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Anguilla', 'cnt_iso' => 'AI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Antarctica', 'cnt_iso' => 'AQ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Antigua and Barbuda', 'cnt_iso' => 'AG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Argentina', 'cnt_iso' => 'AR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Armenia', 'cnt_iso' => 'AM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Aruba', 'cnt_iso' => 'AW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Australia', 'cnt_iso' => 'AU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Austria', 'cnt_iso' => 'AT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Azerbaijan', 'cnt_iso' => 'AZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bahamas', 'cnt_iso' => 'BS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bahrain', 'cnt_iso' => 'BH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bangladesh', 'cnt_iso' => 'BD', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Barbados', 'cnt_iso' => 'BB', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Belarus', 'cnt_iso' => 'BY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Belgium', 'cnt_iso' => 'BE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Belize', 'cnt_iso' => 'BZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Benin', 'cnt_iso' => 'BJ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bermuda', 'cnt_iso' => 'BM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bhutan', 'cnt_iso' => 'BT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bolivia, Plurinational State of', 'cnt_iso' => 'BO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bonaire, Sint Eustatius and Saba', 'cnt_iso' => 'BQ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bosnia and Herzegovina', 'cnt_iso' => 'BA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Botswana', 'cnt_iso' => 'BW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bouvet Island', 'cnt_iso' => 'BV', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Brazil', 'cnt_iso' => 'BR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'British Indian Ocean Territory', 'cnt_iso' => 'IO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Brunei Darussalam', 'cnt_iso' => 'BN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Bulgaria', 'cnt_iso' => 'BG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Burkina Faso', 'cnt_iso' => 'BF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Burundi', 'cnt_iso' => 'BI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Cambodia', 'cnt_iso' => 'KH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Cameroon', 'cnt_iso' => 'CM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Canada', 'cnt_iso' => 'CA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Cape Verde', 'cnt_iso' => 'CV', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Cayman Islands', 'cnt_iso' => 'KY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Central African Republic', 'cnt_iso' => 'CF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Chad', 'cnt_iso' => 'TD', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Chile', 'cnt_iso' => 'CL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'China', 'cnt_iso' => 'CN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Christmas Island', 'cnt_iso' => 'CX', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Cocos (Keeling) Islands', 'cnt_iso' => 'CC', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Colombia', 'cnt_iso' => 'CO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Comoros', 'cnt_iso' => 'KM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Congo', 'cnt_iso' => 'CG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Congo, the Democratic Republic of the', 'cnt_iso' => 'CD', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Cook Islands', 'cnt_iso' => 'CK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Costa Rica', 'cnt_iso' => 'CR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'CAte d Ivoire', 'cnt_iso' => 'CI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Croatia', 'cnt_iso' => 'HR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Cuba', 'cnt_iso' => 'CU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'CuraASao', 'cnt_iso' => 'CW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Cyprus', 'cnt_iso' => 'CY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Czech Republic', 'cnt_iso' => 'CZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Denmark', 'cnt_iso' => 'DK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Djibouti', 'cnt_iso' => 'DJ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Dominica', 'cnt_iso' => 'DM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Dominican Republic', 'cnt_iso' => 'DO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Ecuador', 'cnt_iso' => 'EC', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Egypt', 'cnt_iso' => 'EG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'El Salvador', 'cnt_iso' => 'SV', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Equatorial Guinea', 'cnt_iso' => 'GQ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Eritrea', 'cnt_iso' => 'ER', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Estonia', 'cnt_iso' => 'EE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Ethiopia', 'cnt_iso' => 'ET', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Falkland Islands (Malvinas)', 'cnt_iso' => 'FK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Faroe Islands', 'cnt_iso' => 'FO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Fiji', 'cnt_iso' => 'FJ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Finland', 'cnt_iso' => 'FI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'France', 'cnt_iso' => 'FR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'French Guiana', 'cnt_iso' => 'GF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'French Polynesia', 'cnt_iso' => 'PF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'French Southern Territories', 'cnt_iso' => 'TF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Gabon', 'cnt_iso' => 'GA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Gambia', 'cnt_iso' => 'GM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Georgia', 'cnt_iso' => 'GE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Germany', 'cnt_iso' => 'DE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Ghana', 'cnt_iso' => 'GH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Gibraltar', 'cnt_iso' => 'GI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Greece', 'cnt_iso' => 'GR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Greenland', 'cnt_iso' => 'GL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Grenada', 'cnt_iso' => 'GD', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Guadeloupe', 'cnt_iso' => 'GP', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Guam', 'cnt_iso' => 'GU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Guatemala', 'cnt_iso' => 'GT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Guernsey', 'cnt_iso' => 'GG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Guinea', 'cnt_iso' => 'GN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Guinea-Bissau', 'cnt_iso' => 'GW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Guyana', 'cnt_iso' => 'GY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Haiti', 'cnt_iso' => 'HT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Heard Island and McDonald Islands', 'cnt_iso' => 'HM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Holy See (Vatican City State)', 'cnt_iso' => 'VA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Honduras', 'cnt_iso' => 'HN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Hong Kong', 'cnt_iso' => 'HK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Hungary', 'cnt_iso' => 'HU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Iceland', 'cnt_iso' => 'IS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'India', 'cnt_iso' => 'IN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Indonesia', 'cnt_iso' => 'ID', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Iran, Islamic Republic of', 'cnt_iso' => 'IR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Iraq', 'cnt_iso' => 'IQ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Ireland', 'cnt_iso' => 'IE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Isle of Man', 'cnt_iso' => 'IM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Israel', 'cnt_iso' => 'IL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Italy', 'cnt_iso' => 'IT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Jamaica', 'cnt_iso' => 'JM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Japan', 'cnt_iso' => 'JP', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Jersey', 'cnt_iso' => 'JE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Jordan', 'cnt_iso' => 'JO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Kazakhstan', 'cnt_iso' => 'KZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Kenya', 'cnt_iso' => 'KE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Kiribati', 'cnt_iso' => 'KI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Korea, Democratic Peoples Republic of', 'cnt_iso' => 'KP', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Korea, Republic of', 'cnt_iso' => 'KR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Kuwait', 'cnt_iso' => 'KW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Kyrgyzstan', 'cnt_iso' => 'KG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Lao Peoples Democratic Republic', 'cnt_iso' => 'LA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Latvia', 'cnt_iso' => 'LV', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Lebanon', 'cnt_iso' => 'LB', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Lesotho', 'cnt_iso' => 'LS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Liberia', 'cnt_iso' => 'LR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Libya', 'cnt_iso' => 'LY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Liechtenstein', 'cnt_iso' => 'LI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Lithuania', 'cnt_iso' => 'LT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Luxembourg', 'cnt_iso' => 'LU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Macao', 'cnt_iso' => 'MO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Macedonia, the Former Yugoslav Republic of', 'cnt_iso' => 'MK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Madagascar', 'cnt_iso' => 'MG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Malawi', 'cnt_iso' => 'MW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Malaysia', 'cnt_iso' => 'MY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Maldives', 'cnt_iso' => 'MV', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Mali', 'cnt_iso' => 'ML', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Malta', 'cnt_iso' => 'MT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Marshall Islands', 'cnt_iso' => 'MH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Martinique', 'cnt_iso' => 'MQ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Mauritania', 'cnt_iso' => 'MR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Mauritius', 'cnt_iso' => 'MU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Mayotte', 'cnt_iso' => 'YT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Mexico', 'cnt_iso' => 'MX', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Micronesia, Federated States of', 'cnt_iso' => 'FM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Moldova, Republic of', 'cnt_iso' => 'MD', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Monaco', 'cnt_iso' => 'MC', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Mongolia', 'cnt_iso' => 'MN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Montenegro', 'cnt_iso' => 'ME', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Montserrat', 'cnt_iso' => 'MS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Morocco', 'cnt_iso' => 'MA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Mozambique', 'cnt_iso' => 'MZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Myanmar', 'cnt_iso' => 'MM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Namibia', 'cnt_iso' => 'NA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Nauru', 'cnt_iso' => 'NR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Nepal', 'cnt_iso' => 'NP', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Netherlands', 'cnt_iso' => 'NL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'New Caledonia', 'cnt_iso' => 'NC', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'New Zealand', 'cnt_iso' => 'NZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Nicaragua', 'cnt_iso' => 'NI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Niger', 'cnt_iso' => 'NE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Nigeria', 'cnt_iso' => 'NG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Niue', 'cnt_iso' => 'NU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Norfolk Island', 'cnt_iso' => 'NF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Northern Mariana Islands', 'cnt_iso' => 'MP', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Norway', 'cnt_iso' => 'NO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Oman', 'cnt_iso' => 'OM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Pakistan', 'cnt_iso' => 'PK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Palau', 'cnt_iso' => 'PW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Palestine, State of', 'cnt_iso' => 'PS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Panama', 'cnt_iso' => 'PA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Papua New Guinea', 'cnt_iso' => 'PG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Paraguay', 'cnt_iso' => 'PY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Peru', 'cnt_iso' => 'PE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Philippines', 'cnt_iso' => 'PH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Pitcairn', 'cnt_iso' => 'PN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Poland', 'cnt_iso' => 'PL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Portugal', 'cnt_iso' => 'PT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Puerto Rico', 'cnt_iso' => 'PR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Qatar', 'cnt_iso' => 'QA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'RAunion', 'cnt_iso' => 'RE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Romania', 'cnt_iso' => 'RO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Russian Federation', 'cnt_iso' => 'RU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Rwanda', 'cnt_iso' => 'RW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Saint BarthAlemy', 'cnt_iso' => 'BL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'cnt_iso' => 'SH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Saint Kitts and Nevis', 'cnt_iso' => 'KN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Saint Lucia', 'cnt_iso' => 'LC', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Saint Martin (French part)', 'cnt_iso' => 'MF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Saint Pierre and Miquelon', 'cnt_iso' => 'PM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Saint Vincent and the Grenadines', 'cnt_iso' => 'VC', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Samoa', 'cnt_iso' => 'WS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'San Marino', 'cnt_iso' => 'SM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Sao Tome and Principe', 'cnt_iso' => 'ST', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Saudi Arabia', 'cnt_iso' => 'SA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Senegal', 'cnt_iso' => 'SN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Serbia', 'cnt_iso' => 'RS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Seychelles', 'cnt_iso' => 'SC', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Sierra Leone', 'cnt_iso' => 'SL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Singapore', 'cnt_iso' => 'SG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Sint Maarten (Dutch part)', 'cnt_iso' => 'SX', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Slovakia', 'cnt_iso' => 'SK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Slovenia', 'cnt_iso' => 'SI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Solomon Islands', 'cnt_iso' => 'SB', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Somalia', 'cnt_iso' => 'SO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'South Africa', 'cnt_iso' => 'ZA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'South Georgia and the South Sandwich Islands', 'cnt_iso' => 'GS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'South Sudan', 'cnt_iso' => 'SS', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Spain', 'cnt_iso' => 'ES', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Sri Lanka', 'cnt_iso' => 'LK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Sudan', 'cnt_iso' => 'SD', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Suriname', 'cnt_iso' => 'SR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Svalbard and Jan Mayen', 'cnt_iso' => 'SJ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Swaziland', 'cnt_iso' => 'SZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Sweden', 'cnt_iso' => 'SE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Switzerland', 'cnt_iso' => 'CH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Syrian Arab Republic', 'cnt_iso' => 'SY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Taiwan, Province of China', 'cnt_iso' => 'TW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Tajikistan', 'cnt_iso' => 'TJ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Tanzania, United Republic of', 'cnt_iso' => 'TZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Thailand', 'cnt_iso' => 'TH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Timor-Leste', 'cnt_iso' => 'TL', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Togo', 'cnt_iso' => 'TG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Tokelau', 'cnt_iso' => 'TK', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Tonga', 'cnt_iso' => 'TO', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Trinidad and Tobago', 'cnt_iso' => 'TT', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Tunisia', 'cnt_iso' => 'TN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Turkey', 'cnt_iso' => 'TR', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Turkmenistan', 'cnt_iso' => 'TM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Turks and Caicos Islands', 'cnt_iso' => 'TC', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Tuvalu', 'cnt_iso' => 'TV', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Uganda', 'cnt_iso' => 'UG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Ukraine', 'cnt_iso' => 'UA', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'United Arab Emirates', 'cnt_iso' => 'AE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'United Kingdom', 'cnt_iso' => 'GB', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'United States', 'cnt_iso' => 'US', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'United States Minor Outlying Islands', 'cnt_iso' => 'UM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Uruguay', 'cnt_iso' => 'UY', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Uzbekistan', 'cnt_iso' => 'UZ', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Vanuatu', 'cnt_iso' => 'VU', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Venezuela, Bolivarian Republic of', 'cnt_iso' => 'VE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Viet Nam', 'cnt_iso' => 'VN', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Virgin Islands, British', 'cnt_iso' => 'VG', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Virgin Islands, U.S.', 'cnt_iso' => 'VI', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Wallis and Futuna', 'cnt_iso' => 'WF', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Western Sahara', 'cnt_iso' => 'EH', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Yemen', 'cnt_iso' => 'YE', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Zambia', 'cnt_iso' => 'ZM', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
        DB::table('country')->insert(['cnt_name' => 'Zimbabwe', 'cnt_iso' => 'ZW', 'cnt_active' => 'Y', 'cnt_created_on' => date('Y-m-d H:i:s'), 'cnt_created_by' => 1]);
    }
}
