<?php

use Illuminate\Database\Seeder;

class DashboardItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('dashboard_item')->where('dsi_id', 1)->update(['dsi_title' => 'Planning Job', 'dsi_code' => 'planningJobTable', 'dsi_route' => 'planningJobTable', 'dsi_path' => 'Table/PlanningJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Planning Job Table', 'dsi_color' => '#000000', 'dsi_order' => 13, 'dsi_module_id' => 48, 'dsi_active' => 'Y', 'dsi_uid' => '01e92c78-8d83-363e-abe7-c721b0c4916c', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 2)->update(['dsi_title' => 'In Progress Job', 'dsi_code' => 'inProgressJobTable', 'dsi_route' => 'inProgressJobTable', 'dsi_path' => 'Table/InProgressJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'In Progress Job Table', 'dsi_color' => '#000000', 'dsi_order' => 14, 'dsi_module_id' => 48, 'dsi_active' => 'Y', 'dsi_uid' => '33eb2388-2e6b-3104-ab86-02d446b1d611', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 3)->update(['dsi_title' => 'Total Job InProgress', 'dsi_code' => 'totalInProgressJob', 'dsi_route' => 'totalInProgressJob', 'dsi_path' => 'Widget/TotalJobInProgress', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Job In Progress', 'dsi_color' => '#f0ad4e', 'dsi_order' => 3, 'dsi_module_id' => 48, 'dsi_active' => 'Y', 'dsi_uid' => '04f9b2a2-f22e-304c-914a-09f4d965ab23', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 4)->update(['dsi_title' => 'Total Job Complete', 'dsi_code' => 'totalCompleteJob', 'dsi_route' => 'totalCompleteJob', 'dsi_path' => 'Widget/TotalJobComplete', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Job Complete', 'dsi_color' => '#26b99a', 'dsi_order' => 4, 'dsi_module_id' => 48, 'dsi_active' => 'Y', 'dsi_uid' => '5cfef1d9-285d-3e67-9241-a2686c03e20f', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 5)->update(['dsi_title' => 'Total Job Planning', 'dsi_code' => 'totalPlanningJob', 'dsi_route' => 'totalDraftJob', 'dsi_path' => 'Widget/TotalJobPlanning', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Job Planning', 'dsi_color' => '#555555', 'dsi_order' => 1, 'dsi_module_id' => 48, 'dsi_active' => 'Y', 'dsi_uid' => '43352323-c1fd-32bc-8551-1fa2f9f9605d', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 6)->update(['dsi_title' => 'Total Job Published', 'dsi_code' => 'totalPublishedJob', 'dsi_route' => 'totalPublishedJob', 'dsi_path' => 'Widget/TotalJobPublished', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Job Published', 'dsi_color' => '#d9534f ', 'dsi_order' => 2, 'dsi_module_id' => 48, 'dsi_active' => 'Y', 'dsi_uid' => 'ea678a03-f857-369f-9c90-2c0d6c2921a7', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 7)->update(['dsi_title' => 'Total Import', 'dsi_code' => 'totalImport', 'dsi_route' => 'totalImport', 'dsi_path' => 'Widget/Inklaring/TotalImport', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Import', 'dsi_color' => '#00796b', 'dsi_order' => 5, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srt_id": 8, "jo_srv_id": 2, "jo_srt_name": "Import", "jo_srv_name": "Inklaring"}', 'dsi_uid' => '95cc124e-093c-3439-a5d0-f92293dca853', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 8)->update(['dsi_title' => 'Total Import Container', 'dsi_code' => 'totalImportContainer', 'dsi_route' => 'totalImportContainer', 'dsi_path' => 'Widget/Inklaring/TotalImportContainer', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Import Container', 'dsi_color' => '#2196f3', 'dsi_order' => 6, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srt_id": 6, "jo_srv_id": 2, "jo_srt_name": "Import Container", "jo_srv_name": "Inklaring"}', 'dsi_uid' => 'aa074626-b520-3655-9b14-e960f553e886', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 9)->update(['dsi_title' => 'Total Export', 'dsi_code' => 'totalExport', 'dsi_route' => 'totalExport', 'dsi_path' => 'Widget/Inklaring/TotalExport', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Export', 'dsi_color' => '#d9534f', 'dsi_order' => 7, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srt_id": 9, "jo_srv_id": 2, "jo_srt_name": "Export", "jo_srv_name": "Inklaring"}', 'dsi_uid' => '4010b43f-e675-36d4-b491-1bf8652204ce', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 10)->update(['dsi_title' => 'Total Export Container', 'dsi_code' => 'totalExportContainer', 'dsi_route' => 'totalExportContainer', 'dsi_path' => 'Widget/Inklaring/TotalExportContainer', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Export Container', 'dsi_color' => '#0d47a1', 'dsi_order' => 8, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srt_id": 7, "jo_srv_id": 2, "jo_srt_name": "Export Container", "jo_srv_name": "Inklaring"}', 'dsi_uid' => '48c0a674-2226-3efc-ac91-5ac8f5ba1f28', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 11)->update(['dsi_title' => 'Total Inbound This Month', 'dsi_code' => 'totalInboundItem', 'dsi_route' => 'totalInboundItem', 'dsi_path' => 'Widget/Warehouse/TotalInboundItem', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Inbound This Month', 'dsi_color' => '#2196f3', 'dsi_order' => 9, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => 'e5492a93-7755-3175-95aa-f2f8a22801e7', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 12)->update(['dsi_title' => 'Total Outbound This Month', 'dsi_code' => 'totalOutboundItem', 'dsi_route' => 'totalOutboundItem', 'dsi_path' => 'Widget/Warehouse/TotalOutboundItem', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Outbound This Month', 'dsi_color' => '#0d47a1', 'dsi_order' => 10, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => '6e13436d-875c-355d-9306-98a2bb237731', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 13)->update(['dsi_title' => 'Total Good Stock', 'dsi_code' => 'totalGoodItem', 'dsi_route' => 'totalGoodItem', 'dsi_path' => 'Widget/Warehouse/TotalGoodItem', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Good Stock', 'dsi_color' => '#00796b', 'dsi_order' => 11, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => '0513adba-21b7-3f55-84ee-edab7fabf72c', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 14)->update(['dsi_title' => 'Total Damage Stock', 'dsi_code' => 'totalDamageItem', 'dsi_route' => 'totalDamageItem', 'dsi_path' => 'Widget/Warehouse/TotalDamageItem', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Damage Stock', 'dsi_color' => '#d9534f', 'dsi_order' => 12, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => 'dc529628-914a-3d7d-90c0-e2948abb5105', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 15)->update(['dsi_title' => 'Auto Reload Planning Job', 'dsi_code' => 'autoReloadPlanningJob', 'dsi_route' => 'autoReloadPlanningJob', 'dsi_path' => 'Table/AutoReloadPlanningJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Planning Job Auto Reload', 'dsi_color' => '#000000', 'dsi_order' => 15, 'dsi_active' => 'N', 'dsi_uid' => '40d3f4b8-018f-379e-b517-24da9052411a', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 16)->update(['dsi_title' => 'Auto Reload Progress Job', 'dsi_code' => 'autoReloadProgressJob', 'dsi_route' => 'autoReloadProgressJob', 'dsi_path' => 'Table/AutoReloadProgressJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Progress Job Auto Reload', 'dsi_color' => '#000000', 'dsi_order' => 16, 'dsi_active' => 'N', 'dsi_uid' => '08131377-5ad4-36cc-a699-9718eca9c0d6', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 17)->update(['dsi_title' => 'In Progress Job Trucking', 'dsi_code' => 'inProgressJobTrucking', 'dsi_route' => 'inProgressJobTrucking', 'dsi_path' => 'Table/Trucking/InProgressJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'In Progress Job Trucking', 'dsi_color' => '#000000', 'dsi_order' => 5, 'dsi_module_id' => 47, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 3, "jo_srv_name": "Delivery"}', 'dsi_uid' => '14817081-f8ad-33d8-a625-465b68d4df41', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 18)->update(['dsi_title' => 'Planning Job Trucking', 'dsi_code' => 'planningJobTrucking', 'dsi_route' => 'planningJobTrucking', 'dsi_path' => 'Table/Trucking/PlanningJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Planning Job Trucking', 'dsi_color' => '#000000', 'dsi_order' => 6, 'dsi_module_id' => 47, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 3, "jo_srv_name": "Delivery"}', 'dsi_uid' => '69987778-47c9-363d-95b1-af7bd91cb546', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->where('dsi_id', 19)->update(['dsi_title' => 'Warehouse Arrive Soon', 'dsi_code' => 'warehouseArriveSoon', 'dsi_route' => 'warehouseArriveSoon', 'dsi_path' => 'Table/Warehouse/ArriveSoon', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Warehouse Arrive Soon', 'dsi_color' => '#000000', 'dsi_order' => 19, 'dsi_active' => 'N', 'dsi_uid' => '74c3636c-1c99-3f9e-94ec-7c05fade299a', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);

        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Planning Warehouse', 'dsi_code' => 'totalPlanningWh', 'dsi_route' => 'totalDraftJob', 'dsi_path' => 'Widget/TotalJobPlanning', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Planning Warehouse', 'dsi_color' => '#555555', 'dsi_order' => 1, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => '66d587bc-b241-4405-9179-f681c1412b76', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Published Warehouse', 'dsi_code' => 'totalPublishedWh', 'dsi_route' => 'totalPublishedJob', 'dsi_path' => 'Widget/TotalJobPublished', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Published Warehouse', 'dsi_color' => '#d9534f', 'dsi_order' => 2, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => 'c62684e5-85b6-4fa9-8951-ef46542b961e', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total InProgress Warehouse', 'dsi_code' => 'totalInProgressWh', 'dsi_route' => 'totalInProgressJob', 'dsi_path' => 'Widget/TotalJobInProgress', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total In Progress Warehouse', 'dsi_color' => '#f0ad4e', 'dsi_order' => 3, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => '9a77891c-9c61-41c8-9993-829d8bcddb07', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Complete Warehouse', 'dsi_code' => 'totalCompleteWh', 'dsi_route' => 'totalCompleteJob', 'dsi_path' => 'Widget/TotalJobComplete', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Complete Warehouse', 'dsi_color' => '#26b99a', 'dsi_order' => 4, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => '2351eea1-6aa5-4700-8ab6-6754e8cc5caf', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Planning Inklaring', 'dsi_code' => 'totalPlanningInk', 'dsi_route' => 'totalDraftJob', 'dsi_path' => 'Widget/TotalJobPlanning', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Planning Inklaring', 'dsi_color' => '#555555', 'dsi_order' => 1, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 2, "jo_srv_name": "Inklaring"}', 'dsi_uid' => '375d8c5c-680e-4e68-86c2-2b441738b108', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Published Inklaring', 'dsi_code' => 'totalPublishedInk', 'dsi_route' => 'totalPublishedJob', 'dsi_path' => 'Widget/TotalJobPublished', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Published Inklaring', 'dsi_color' => '#d9534f', 'dsi_order' => 2, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 2, "jo_srv_name": "Inklaring"}', 'dsi_uid' => '972ab6ca-a34c-4921-843e-96316e907de3', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total InProgress Inklaring', 'dsi_code' => 'totalInProgressInk', 'dsi_route' => 'totalInProgressJob', 'dsi_path' => 'Widget/TotalJobInProgress', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total In Progress Inklaring', 'dsi_color' => '#f0ad4e', 'dsi_order' => 3, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 2, "jo_srv_name": "Inklaring"}', 'dsi_uid' => 'ba9a5a85-c9ba-4409-ba54-c666e4ac15f5', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Complete Inklaring', 'dsi_code' => 'totalCompleteInk', 'dsi_route' => 'totalCompleteJob', 'dsi_path' => 'Widget/TotalJobComplete', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Complete Inklaring', 'dsi_color' => '#26b99a', 'dsi_order' => 4, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 2, "jo_srv_name": "Inklaring"}', 'dsi_uid' => 'fcfef283-42cb-4ace-9166-4673a7cccc13', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Planning Delivery', 'dsi_code' => 'totalPlanningDv', 'dsi_route' => 'totalDraftJob', 'dsi_path' => 'Widget/TotalJobPlanning', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Planning Delivery', 'dsi_color' => '#555555', 'dsi_order' => 1, 'dsi_module_id' => 47, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 3, "jo_srv_name": "Delivery"}', 'dsi_uid' => '9b6ee311-0a25-4593-a2c1-6f32d9f7e73e', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Published Delivery', 'dsi_code' => 'totalPublishedDv', 'dsi_route' => 'totalPublishedJob', 'dsi_path' => 'Widget/TotalJobPublished', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Published Delivery', 'dsi_color' => '#d9534f', 'dsi_order' => 2, 'dsi_module_id' => 47, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 3, "jo_srv_name": "Delivery"}', 'dsi_uid' => '086a652b-5e83-4621-979c-e890f53061a1', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total InProgress Delivery', 'dsi_code' => 'totalInProgressDv', 'dsi_route' => 'totalInProgressJob', 'dsi_path' => 'Widget/TotalJobInProgress', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total In Progress Delivery', 'dsi_color' => '#f0ad4e', 'dsi_order' => 3, 'dsi_module_id' => 47, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 3, "jo_srv_name": "Delivery"}', 'dsi_uid' => '4f2e6e58-161b-4a9e-8d21-3ea4dce829d5', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Total Complete Delivery', 'dsi_code' => 'totalCompleteDv', 'dsi_route' => 'totalCompleteJob', 'dsi_path' => 'Widget/TotalJobComplete', 'dsi_height' => 100, 'dsi_grid_large' => 3, 'dsi_grid_medium' => 4, 'dsi_grid_small' => 6, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Total Complete Delivery', 'dsi_color' => '#26b99a', 'dsi_order' => 4, 'dsi_module_id' => 47, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 3, "jo_srv_name": "Delivery"}', 'dsi_uid' => 'c26a1cae-03e9-4488-bdec-4ca5ea089f72', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Planning Warehouse', 'dsi_code' => 'planningWhTable', 'dsi_route' => 'planningJobTable', 'dsi_path' => 'Table/PlanningJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Planning Warehouse Table', 'dsi_color' => '#000000', 'dsi_order' => 5, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => '99a389bd-5282-4dec-bb4f-6fba6b6ccbb7', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'In Progress Warehouse', 'dsi_code' => 'inProgressWhTable', 'dsi_route' => 'inProgressJobTable', 'dsi_path' => 'Table/InProgressJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'In Progress Warehouse Table', 'dsi_color' => '#000000', 'dsi_order' => 6, 'dsi_module_id' => 45, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 1, "jo_srv_name": "Warehouse"}', 'dsi_uid' => '66557e0e-5f69-4e4b-a7e5-8a891d62544b', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'Planning Inklaring', 'dsi_code' => 'planningInkTable', 'dsi_route' => 'planningJobTable', 'dsi_path' => 'Table/PlanningJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'Planning Inklaring Table', 'dsi_color' => '#000000', 'dsi_order' => 9, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 2, "jo_srv_name": "Inklaring"}', 'dsi_uid' => 'a65b5fc3-2615-457f-9114-bb24b0f55952', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
        DB::table('dashboard_item')->insert(['dsi_title' => 'In Progress Inklaring', 'dsi_code' => 'inProgressInkTable', 'dsi_route' => 'inProgressJobTable', 'dsi_path' => 'Table/InProgressJob', 'dsi_height' => 300, 'dsi_grid_large' => 6, 'dsi_grid_medium' => 6, 'dsi_grid_small' => 12, 'dsi_grid_xsmall' => 12, 'dsi_description' => 'In Progress Inklaring Table', 'dsi_color' => '#000000', 'dsi_order' => 10, 'dsi_module_id' => 46, 'dsi_active' => 'Y', 'dsi_parameter' => '{"jo_srv_id": 2, "jo_srv_name": "Inklaring"}', 'dsi_uid' => '2e087fdc-f749-4fb4-93e6-b93fcd94e30e', 'dsi_created_on' => date('Y-m-d H:i:s'), 'dsi_created_by' => 1]);
    }
}
