<?php

use Illuminate\Database\Seeder;

class PageRightSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        # Quotaion
        DB::table('page_right')->where('pr_id', 572)->update(['pr_default' => 'N']);
        DB::table('page_right')->where('pr_id', 575)->update(['pr_default' => 'N']);
        DB::table('page_right')->where('pr_id', 578)->update(['pr_default' => 'N']);
        DB::table('page_right')->where('pr_id', 604)->update(['pr_default' => 'N']);
        DB::table('page_right')->where('pr_id', 607)->update(['pr_default' => 'N']);
        DB::table('page_right')->where('pr_id', 613)->update(['pr_default' => 'N']);
        DB::table('page_right')->where('pr_id', 173)->update(['pr_default' => 'N']);
        DB::table('page_right')->insert(['pr_pg_id' => 15, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow user to update data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '97a7926b-62a1-3301-b888-5c8baf0646f2', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 17, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow user to update.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '5abc84b6-5dd4-38df-a538-7a62aa263a0b', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 1, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow user to update data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '14bbf1f0-1d85-3459-9828-736d730e73eb', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 61, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'd552ed86-7727-3488-8eda-60820b456425', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 160, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '775cf953-5505-3981-b457-4a4ab11654fc', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 161, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '41d90f6f-cf0b-3177-8a78-c44a67de249e', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 13, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '20ee378b-f439-37e9-8151-862788be7733', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 43, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '3fedfbaf-9566-377f-ae2a-b23c9f8fa29d', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 55, 'pr_name' => 'AllowUpdate', 'pr_description' => 'AllowUpdate', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '37b0f238-9df1-31c3-bcff-5e9fff64e450', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 57, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '396497e9-3573-310c-b0b6-8bbc363f001b', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 59, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'ed9f020c-5320-3092-b288-1fbb28dbe004', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 63, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'af4cf922-0ae3-3f1a-84b9-348d32bcaeea', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 65, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'f35f3ef3-c0d2-32ea-b9eb-12e43e9fde65', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 19, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '4cf6eefc-e199-36fb-8b01-237ed490b9b7', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 49, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'a763f325-d19a-3990-adc2-d947d4f1d4f4', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 67, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '92e07ac0-f0ec-34b8-a167-7ebd242394ea', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 80, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'c9104995-d498-3004-a79b-5ac67738b1b1', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 96, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'fb9be2a1-cc11-39eb-8194-650ff6e5d090', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 98, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '18863fb2-b2d2-37ae-9ea2-c982150bc6a7', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 100, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '4ebc16f6-a6f7-373c-80d9-bf6110a053ce', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 102, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '6f411973-ff18-39ac-a0b9-bcc62b60efe8', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 118, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'b0f2917c-9f01-3cd4-8589-a8cf9e0d26e4', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 149, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '80aa332f-0fb5-32ae-9c6e-7bc4a2a0c3b0', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 151, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'c92e50b8-242b-3da0-9ff1-ed65f39d0a70', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 153, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '6697f91a-58af-30cc-b0e7-3032e520cb05', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 155, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '2aa79eea-2ddf-3816-a9b6-325425e87495', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 156, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '8d42f2cb-5699-3e51-88a1-73e58676b3c0', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 167, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'b9c5a76b-52bc-337d-acae-88c64b9c3514', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 169, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '784ac789-43fa-3134-8129-6d2ce48f96a4', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 122, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'b48ada9b-4249-332a-bbff-eabf47313d9c', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 172, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '2da8adc8-6015-311c-a224-0fd320922842', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 179, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'c5614cf7-175c-3a70-9a51-497c2a18b7db', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 182, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'a769a1a3-ccbb-37dd-9b97-827d175b1bb1', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 185, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '34278d2b-c24f-38fb-8653-b346400b7cf8', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 187, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'fa06a7de-a3b5-3970-80a1-ea0f3ce4af71', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 191, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '3259237d-b9bb-3803-a508-f0ca1bef9d36', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 193, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '4d9edce4-5ca7-3c4c-8608-b770a6b78189', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 196, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '620625e3-0a66-33a4-891f-6f9195b5712c', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 106, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'e3989252-aea8-3e76-8e6b-38a128dda5e4', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 119, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'c19d65d7-04a2-33cd-90e9-bdfd6b3f3634', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 79, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '803f34b1-64f8-3c5c-a056-ffebd909c208', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 33, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow Update', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '4f8aaf08-1bd2-3fdd-b9ac-33df96a91f8b', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);

        # invoice
        DB::table('page_right')->insert(['pr_pg_id' => 162, 'pr_name' => 'AllowDelete', 'pr_description' => 'AllowDelete', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'add8a661-3918-3067-8904-61ba859b0932', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 157, 'pr_name' => 'AllowDelete', 'pr_description' => 'AllowDelete', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '7df5a122-1663-3a9d-9406-40ae1c5d8805', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 120, 'pr_name' => 'AllowPublishWithoutQuotation', 'pr_description' => 'AllowPublishWithoutQuotation', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'd50c9982-650a-3509-9cf5-354b030886a8', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 120, 'pr_name' => 'AllowSeeQuotation', 'pr_description' => 'AllowSeeQuotation', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'e5eeeb71-3e0c-38a3-a55a-a806b3947cd5', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 121, 'pr_name' => 'AllowSeeQuotation', 'pr_description' => 'AllowSeeQuotation', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '36f3098d-65aa-3238-b6fc-9bdad5c939f7', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 124, 'pr_name' => 'AllowInsertSalesWithoutQuotation', 'pr_description' => 'AllowInsertSalesWithoutQuotation', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '640ff793-109f-3942-956a-72a8e1a02385', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 124, 'pr_name' => 'AllowInsertPurchaseWithoutQuotation', 'pr_description' => 'AllowInsertPurchaseWithoutQuotation', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'bd910ce8-8833-3835-a1c9-fda8c7a14993', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 124, 'pr_name' => 'AllowPublishWithoutFinanceData', 'pr_description' => 'AllowPublishWithoutFinanceData', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '4d9ec90e-a6bc-3836-8bfb-8f8da0454f3e', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 124, 'pr_name' => 'AllowSeeDeposit', 'pr_description' => 'AllowSeeDeposit', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '8a7eb164-701c-3088-a2d4-d09fd81521b3', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 124, 'pr_name' => 'AllowUpdateDeposit', 'pr_description' => 'AllowUpdateDeposit', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '75aa1554-b697-3d27-a950-aa0272a0ac6a', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 125, 'pr_name' => 'AllowSeeDeposit', 'pr_description' => 'AllowSeeDeposit', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'ece11ee7-1340-36fb-be34-ffef7edceafb', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 146, 'pr_name' => 'AllowSeeDeposit', 'pr_description' => 'AllowSeeDeposit', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '016a0326-ed67-3896-9211-d0997940f810', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 145, 'pr_name' => 'AllowSeeDeposit', 'pr_description' => 'AllowSeeDeposit', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '6067ec5f-6c0d-3725-9da1-e9afd97023dc', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 145, 'pr_name' => 'AllowUpdateDeposit', 'pr_description' => 'AllowUpdateDeposit', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'be5b486b-c8ed-3697-907a-6356cd492b1e', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 145, 'pr_name' => 'AllowPublishWithoutFinanceData', 'pr_description' => 'AllowPublishWithoutFinanceData', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '31bc8e8e-6b25-3b47-b858-b4b7c1f7d894', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 145, 'pr_name' => 'AllowInsertPurchaseWithoutQuotation', 'pr_description' => 'AllowInsertPurchaseWithoutQuotation', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '20d405e6-3041-3827-92e1-1bababb3f2ae', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 145, 'pr_name' => 'AllowInsertSalesWithoutQuotation', 'pr_description' => 'AllowInsertSalesWithoutQuotation', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'b3e19e91-9129-3184-b1ee-fae795697378', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);

        DB::table('page_right')->where('pr_id', 683)->update(['pr_default' => 'Y']);
        DB::table('page_right')->where('pr_id', 684)->update(['pr_default' => 'Y']);
        DB::table('page_right')->insert(['pr_pg_id' => 62, 'pr_name' => 'AllowDelete', 'pr_description' => 'AllowDelete', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '3ef3e9f2-f7ab-38bd-898b-f6148a72b8e5', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 111, 'pr_name' => 'AllowDelete', 'pr_description' => 'AllowDelete', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '5f27a7cc-6296-3748-b7be-6c95eb943ecc', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 111, 'pr_name' => 'AllowApproveInklaring', 'pr_description' => 'AllowApproveInklaring', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'b9d53334-3826-3593-bd84-2ec0c3cf5ee9', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 111, 'pr_name' => 'AllowApproveTrucking', 'pr_description' => 'AllowApproveTrucking', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '3322f1f2-62db-3a4f-a4a8-cca2e8136c55', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 111, 'pr_name' => 'AllowApproveWarehouse', 'pr_description' => 'AllowApproveWarehouse', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '140c35c7-1d6c-3d04-bf0b-f46d7b8013f8', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 120, 'pr_name' => 'AllowSeeDeposit', 'pr_description' => 'AllowSeeDeposit', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'e4b4ed33-9c73-3e80-a679-2be652502151', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 121, 'pr_name' => 'AllowSeeDeposit', 'pr_description' => 'AllowSeeDeposit', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '4979b7d2-2bd7-3eb4-acb2-f8100368eed2', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);

        # Electronic Account
        DB::table('page_right')->insert(['pr_pg_id' => 268, 'pr_name' => 'AllowInsert', 'pr_description' => 'Allow user to insert new data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => 'd6227b6e-96db-3df4-a6ef-1dbd6905c073', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 268, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow user to update data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '200eb4ba-2d87-38fd-9aab-28fdc1eb5c3f', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 268, 'pr_name' => 'AllowExportXls', 'pr_description' => 'Allow user to export the data to excel file.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '2d77c27b-14a6-3faf-af41-fef2f3511102', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 268, 'pr_name' => 'AllowSeeAllUserAccount', 'pr_description' => 'Allow See All User Account', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'edfc4a2f-0363-3731-9193-334a54d0c982', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 269, 'pr_name' => 'AllowInsert', 'pr_description' => 'Allow user to insert new data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '8bac4370-1a5f-32f9-a9fb-46d76cd1f77a', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 269, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow user to update the data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '40a01b2d-2199-3a81-b132-cb830f6bb554', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 269, 'pr_name' => 'AllowDelete', 'pr_description' => 'Allow user to delete the data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '9abac2d5-bbfc-303c-9080-544e5c39f2d1', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 269, 'pr_name' => 'AllowInsertAccountForOtherUser', 'pr_description' => 'Allow Insert Account For Other User', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '6f43663b-f00a-345e-834e-05e9c0c98943', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 269, 'pr_name' => 'AllowTopUpFromMainAccount', 'pr_description' => 'Allow Top Up from main bank account.', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '8325990b-44ea-36de-9262-30bb6bd305d9', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 270, 'pr_name' => 'AllowInsert', 'pr_description' => 'Allow user to insert new data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '3a63194b-6154-3fe8-80b5-f59f017dfed5', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 270, 'pr_name' => 'AllowUpdate', 'pr_description' => 'Allow user to update data.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '708c93c2-f54d-32ae-879c-dd34bf6935d5', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 270, 'pr_name' => 'AllowExportXls', 'pr_description' => 'Allow user to export the data to excel file.', 'pr_default' => 'Y', 'pr_active' => 'Y', 'pr_uid' => '7ed50ba8-2fca-32e7-86b9-cb952f6d8773', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 270, 'pr_name' => 'AllowSeeAllUserAccount', 'pr_description' => 'Allow See All User Account', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '51d88199-3e75-3c36-95e0-8a86f146a91f', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);

        # Job order
        DB::table('page_right')->insert(['pr_pg_id' => 124, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '8024b6e6-993b-3f42-b93f-6ac35d405729', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 145, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => 'dce4391c-9f4c-34ad-89d9-46b0250fd165', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 78, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '7aaa062e-a900-38d2-b449-c2f8b878c52f', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 84, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '6d0ac541-68ca-3ad8-a86f-c1c656a951be', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 88, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '211408c3-4f36-39c4-b318-3e34fc6e5155', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 91, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '373bb6f9-6c3b-32ba-ab5a-f9060c65bbdd', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 94, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '7bff8053-ba53-3756-9c82-8e1934e015e8', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 170, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '7bcda176-25d4-31d5-979e-73c28db1049c', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
        DB::table('page_right')->insert(['pr_pg_id' => 173, 'pr_name' => 'AllowUpdateSalesReimbursement', 'pr_description' => 'AllowUpdateSalesReimbursement', 'pr_default' => 'N', 'pr_active' => 'Y', 'pr_uid' => '6fff2242-ef99-3c4a-90db-7e857b753faa', 'pr_created_on' => date('Y-m-d H:i:s'), 'pr_created_by' => 1]);
    }
}
